# Add account credentials and API keys here.
# See http://railsapps.github.io/rails-environment-variables.html
# This file should be listed in .gitignore to keep your settings secret!
# Each entry sets a local environment variable and overrides ENV variables in the Unix shell.
# For example, setting:
# GMAIL_USERNAME: Your_Gmail_Username
# makes 'Your_Gmail_Username' available as ENV["GMAIL_USERNAME"]
# Add application configuration variables here, as shown below.
#
GMAIL_USERNAME: orm1mini@gmail.com
GMAIL_PASSWORD: qwerty1234567
ADMIN_NAME: babazina
ADMIN_EMAIL: lesha0-lesha0@mail.ru
ADMIN_PASSWORD: 55568402
ROLES: [admin, moderator, expectation]
STATUSES: [Waiting for Staff Response,Waiting for Customer, On Hold, Completed]
